### ISSUE TITLE
Добавить конфиг в проект

### ISSUE THREAD

**Issue by vasiliev-alexey** [penguin-astronaut/weather-app#3]
Вынести статичиеские параметры в конфиг, например

<code>
  const key = "619769815d2e235e82cf7ee1a4435658";   
  ...	
</code>

**Comment by penguin-astronaut** [comment]
а надо ли добавлять этот файл в .gitignore или в рамках ДЗ не нужно?

**Comment by vasiliev-alexey** [comment]
нет, конфиг часть проекта.
Имеется в виду - чтобы была возможность изменения конфигурации без пробегания по исходному коду , 
(например если ключ протухнет - то меняем его в 1 месте,  не трогая логику)
